# -*- coding: utf-8 -*-
"""Project_Text_Summarization_Data_Preprocessing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/185ar78NjuvE_vJ5mfeIpPoJmZt6UZl1H
"""

# Project/Text Summarization - Data preprocessing
# Author: Kopal Rastogi
# Created: 05-May-2021
# Keywords: None
# Assumptions: None

print('Importing Libraries ... ',end='')
import re
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd
import pickle as pkl
print('Done')

#Read data
def read_data(path):
    news1_df = pd.read_csv(path+'news_summary.csv', encoding='latin-1', usecols=['headlines', 'text','ctext'])
    # Merge text and ctext
    news1_df['text']=news1_df['text']+" "+news1_df['ctext']
    news1_df=news1_df.drop(['ctext'],axis=1)
    news2_df = pd.read_csv(path+'news_summary_more.csv', encoding='latin-1')
    data = pd.concat([news1_df, news2_df], axis=0).reset_index(drop=True)
    return data

data = read_data('./Datasets/news_summary/')
data.head()

# Data Description
data.describe()

# Get shape
data.shape

# Checking for null values
data.isnull().sum()

# Drop the rows with Null
data.dropna(axis=0,how ='any',inplace=True)
data.shape

# Dump the cleaned data
pkl.dump(data,open('newsdata.pkl','wb'))

data=pkl.load( open( "newsdata.pkl", "rb" ))

data.drop_duplicates(inplace=True)
data.shape

# Commented out IPython magic to ensure Python compatibility.
# %%time
# data.to_csv('news_data.csv',index=False)